words=["aback", "abaft", "abandoned", "abashed", "aberrant", "abiding", "abject", "ablaze", "able", "abnormal", "aboard", "aboriginal", "abortive", "abounding", "abrasive",
    "abrupt", "absent", "absorbed", "absorbing", "abstract", "absurd", "abundant", "abusive", "acceptable", "accessible", "accidental", "accurate", "acid", "acidic", "acoustic",
    "acrid", "actually", "ad", "adamant", "adaptable", "addicted", "adhesive", "adjoining", "adorable", "adventurous", "afraid", "aggressive", "agonizing", "agreeable",
    "ahead", "ajar", "alcoholic", "alert", "alike", "alive", "alleged", "alluring", "amazing", "ambiguous", "ambitious", "amuck", "amused", "amusing", "ancient", "angry",
    "animated", "annoyed", "annoying", "anxious", "apathetic", "aquatic", "aromatic", "arrogant", "ashamed", "aspiring", "assorted", "astonishing", "attractive", "auspicious",
    "automatic", "available", "average", "awake", "aware", "awesome", "awful", "axiomatic", "barbarous", "bashful", "bawdy", "beautiful", "befitting", "belligerent", "beneficial",
    "bent", "berserk", "best", "better", "bewildered", "big", "billowy", "bite-sized", "bitter", "bizarre", "black", "black-and-white", "bloody", "blue", "blue-eyed",
    "blushing", "boiling", "boorish", "bored", "boring", "bouncy", "boundless", "brainy", "brash", "brave", "brawny", "breakable", "breezy", "brief", "bright", "bright-eyed",
    "broken", "brown", "bumpy", "burly", "bustling", "busy", "cagey", "calculating", "callous", "calm", "capable", "capricious", "careful", "careless", "caring", "cautious",
    "ceaseless", "certain", "changeable", "charming", "cheap", "cheerful", "chemical", "chief", "childlike", "chilly", "chivalrous", "chubby", "chunky", "clammy", "classy",
    "clean", "clear", "clever", "cloistered", "cloudy", "closed", "clumsy", "cluttered", "coherent", "cold", "colorful", "colossal", "combative", "comfortable", "common",
    "complete", "complex", "concerned", "condemned", "confused", "conscious", "cooing", "cool", "cooperative", "coordinated", "courageous", "cowardly", "crabby", "craven",
    "crazy", "creepy", "crooked", "crowded", "cruel", "cuddly", "cultured", "cumbersome", "curious", "curly", "curved", "cute", "cut", "cyan", "cynical", "daffy", "daily",
    "damaged", "damaging", "damp", "dangerous", "dapper", "dark", "dashing", "dazzling", "dead", "deadpan", "deafening", "dear", "debonair", "decisive", "decorous", "deep",
    "defeated", "defective", "defiant", "delicate", "delicious", "delightful", "demonic", "dense", "depressed", "deranged", "descriptive", "deserted", "detailed", "determined",
    "devilish", "didactic", "different", "difficult", "diligent", "direful", "dirty", "disagreeable", "disastrous", "discreet", "disgusted", "disgusting", "distinct", "distracted",
    "disturbed", "divergent", "dizzy", "domineering", "dopey", "doubtful", "drab", "draconian", "dramatic", "dreary", "dry", "dull", "dusty", "dynamic", "dysfunctional",
    "eager", "ear-piercing", "earthy", "easy", "eatable", "economic", "educated", "efficacious", "efficient", "eight", "elastic", "elated", "elderly", "electric", "elegant",
    "elfin", "elite", "embarrassed", "eminent", "empty", "enchanted", "enchanting", "encouraging", "endurable", "energetic", "enormous", "entertaining", "enthusiastic",
    "envious", "equable", "equal", "erect", "erratic", "ethereal", "evanescent", "evasive", "even", "excellent", "excited", "exciting", "exotic", "expensive", "extra-large",
    "exuberant", "exultant", "exulting", "fabulous", "faint", "fair", "faithful", "fallacious", "false", "familiar", "famous", "fancy", "fantastic", "far", "fascinated",
    "fast", "fat", "faulty", "fearful", "fearless", "feeble", "feigned", "female", "fertile", "festive", "few", "fierce", "filthy", "fine", "finicky", "first", "five",
    "fixed", "flagrant", "flaky", "flashy", "flat", "flawless", "flimsy", "flippant", "flowery", "fluffy", "fluttering", "foamy", "foolish", "foregoing"
  ]
